server:
  port: 8000

spring:
  application:
    name: chat

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.znmnjzfrtqxqfufwrxqq
    password: Postgre123
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000 # 30s
      max-lifetime: 1800000 # 30 phút
      connection-timeout: 30000 # 30s
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0

  redis:
    host: kind-lab-13771.upstash.io
    port: 6379
    password: ATXLAAIncDI3ZjJiODYyYTRlMzI0YzgzYjhmZWI4NGIxYmE5YmFkYXAyMTM3NzE
    ssl: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  validation:
    enabled: true

api:
  prefix: /api/v1

keys:
  private: PRIVATE_KEY
  public: PUBLIC_KEY

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: http://localhost:8000/api/v1/auth/google/callback

jwt:
  secret: "TDungx2k3TDungx2k3TDungx2k3TDungx2k3TDungx2k3TDungx2k3"
  expiration: 86400000

logging:
  level:
    org.springframework.data.redis: DEBUG
