server:
  port: 8000

spring:
  application:
    name: chat

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.znmnjzfrtqxqfufwrxqq
    password: Postgre123
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000        # 30s
      max-lifetime: 1800000      # 30 phút
      connection-timeout: 30000  # 30s
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0

  redis:
    host: valid-mongrel-44979.upstash.io
    port: 6379
    password: Aa-zAAIjcDFjYzg4NDZjZDkyNzQ0NWZjYjE2NzViZWE3NDljZDdkNXAxMA
    ssl: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  validation:
    enabled: true

api:
  prefix: /api/v1

keys:
  private: PRIVATE_KEY
  public: PUBLIC_KEY

logging:
  level:
    org.springframework.data.redis: DEBUG